---
- name: "{{ 'Deploying' if action=='create' else 'Removing' }} Workload"
  hosts: localhost
  connection: local
  tasks: 
  - name: "Including variables..."
    include_vars: "../{{ ocp_version | mandatory }}.x/my_vars.yml"
  
  - name: "Setting remote facts..."
    set_fact:
      guid: "{{ guid }}"
      subdomain_base_suffix: "{{ subdomain_base_suffix }}"
      output_dir: "{{ output_dir }}"
  
  - name: "Adding a new host"
    add_host:
      hostname: "bastion.{{ guid }}{{ subdomain_base_suffix }}"
      groups: "remote"
       
  - name: "Including secrets and workload variables..."
    include_vars: "{{ item }}"
    loop:
      - "../secret.yml"
      - "./workload_vars/{{ workload }}.yml"

  - shell: "ansible-playbook -i bastion.{{ guid }}{{ subdomain_base_suffix }}, {{ agnosticd_home | mandatory }}/ansible/configs/ocp-workloads/ocp-workload.yml -e ansible_ssh_private_key_file={{ output_dir }}/{{ guid }}key -e ansible_user=ec2-user -e ocp_workload=ocp-workload-{{ workload | mandatory }} -e ACTION={{ action }} -e @../secret.yml -e @./workload_vars/{{ workload | mandatory }}.yml -e playbook_dir={{ agnosticd_home }}"
    register: output
    ignore_errors: yes

  - debug: 
      msg: "{{ output.stdout }}"

  - fail:
      msg: "Workload deployment failed"
    when: output.rc != 0
